name: Run app.py every Thursday at 6 AM PT

on:
  schedule:
    - cron: '14 14 * * 4'  # Runs at 14:00 UTC every Thursday (6 AM PT)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify Python 3.10 or 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python app.py
      env:
        WHATSAPP_URL: ${{ secrets.WHATSAPP_URL }}
        NUMBER: ${{ secrets.NUMBER }}