name: Run trash_in.py every Tuesday at 9 AM PT

on:
  # schedule:
  #     - cron: '16 16 * * 5'  # Runs at 16:00 UTC every Friday (9 AM PT)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify Python 3.10 or 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python trash_in.py
      env:
        WHATSAPP_URL: ${{ secrets.WHATSAPP_URL }}
        NUMBER: ${{ secrets.NUMBER }}